define({
   btn_cancel:"Cancel",
        btn_ok:"Ok",
        btn_reset:"Reset",
        btn_submit:"Submit",
        btn_delete:"Delete",
		btn_update:"Update",
		btn_new:"New",
		btn_clean:"Clean",
		btn_filter:"Filter",
        login:"Login",
        logout:"Logout",
        logout_alert:"Are you sure you want to logout?",
        login_username:"Username",
        login_pwd:"Password",
        login_err:"Yor username or password is incorrect ",
        internal_server_error:"Internal Server Error",
        pw_forgot:"Forgot password?",
        pw_forgot_tips:"You must have a valid e-mail address entered in Mepla, so the password can be sent successfully. <br>  Enter your username and the registered email address below to receive a new password.",
        email_invalid:"The entered email is invalid.",
        username_email_invalid:"The entered username or email is invalid.",
        chg_pw:"Change password",
        chg_pw_tips:"Please enter you old password and new password below.",
        new_pw:"New password",
        old_pw:"Old password",
        new_pw_no_match:"Your new passwords do not match. Please re-enter them.",
        pw_send:"Your password will be reset and you'll receive a new password by email.",
        pw_changed:"The password has been successfully changed."
	
	
});