define({
		
		btn_cancel:"取消",
        btn_ok:"确认",
        btn_reset:"重置",
        btn_submit:"提交",
        btn_delete:"删除",
		btn_update:"更改",
		btn_new:"新建",
		btn_clean:"清空",
		btn_filter:"过滤",
        login:"登录",
        logout:"登出",
        logout_alert:"您确定要登出吗？",
        login_username:"用户名",
        login_pwd:"密码",
        login_err:"您输入的用户名或者密码不正确",
        internal_server_error:"服务器内部错误，需要了解情况，请进一步联系您的管理员",
        pw_forgot:"忘记密码?",
        pw_forgot_tips:"您首先需要在管理系统中拥有有效的电子邮件地址， 以便新的密码能够成功的被接受到。 <br>  请输入您的用户名和已登记的有效的电子邮件地址。",
        email_invalid:"你输入的电子邮件地址无效",
        username_email_invalid:"你输入的用户名或者电子邮件地址无效",
        chg_pw:"变更用户密码",
        passwd_recall:"取回密码",
        chg_pw_tips:"请您输入当前密码和新的密码。",
        new_pw:"新密码",
        old_pw:"当前密码",
        new_pw_no_match:"您输入的新密码前后不匹配，请您再输入一次。",
        pw_send:"您的密码已经被重置，新的密码将由系统自动发至到您的邮箱内，如果您在5分钟内还没有收到邮件，请您重试或者联系您的系统管理员。",
        pw_changed:"密码已经成功的被更改。",
        email:"电子邮件",
        pw_forgot_tips:"您首先需要在Mepla中拥有有效的电子邮件地址， 以便新的密码能够成功的被接受到。 <br>  请输入您的用户名和已登记的有效的电子邮件地址。",
        password_format:"密码在4位到10位之间，且最少有一个是数字",
        operation_error:"本项操作当前无法完成，请您稍后再试或者联系您的管理员",
        fields_empty:"请正确填写相应的项目",
        welcome:"欢迎",
        article_mgt:"条目管理",
        calendar_mgt:"日历管理",
        team_calendar:"团队日历",
        public_calendar:"公共日历",
        event_properties:"事件面板",
        summary:"摘要",
        start:"开始",
        end:"结束",
        all_day:"全天",
        calendar:"日历"

	
});